=== Exymat/haproxy-vscode/syntaxes/tmlanguage.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "TextMate Grammar",
  "type": "object",
  "required": [
    "name",
    "scopeName",
    "patterns",
    "repository"
  ],
  "properties": {
    "$schema": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "scopeName": {
      "type": "string"
    },
    "fileTypes": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "firstLineMatch": {
      "type": "string"
    },
    "foldingStartMarker": {
      "type": "string"
    },
    "foldingStopMarker": {
      "type": "string"
    },
    "patterns": {
      "$ref": "#/$defs/patternList"
    },
    "repository": {
      "type": "object",
      "additionalProperties": {
        "$ref": "#/$defs/ruleContainer"
      }
    },
    "injections": {
      "type": "object",
      "additionalProperties": {
        "$ref": "#/$defs/ruleContainer"
      }
    }
  },
  "additionalProperties": true,
  "$defs": {
    "patternList": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/pattern"
      }
    },
    "captures": {
      "type": "object",
      "patternProperties": {
        "^[0-9]+$": {
          "$ref": "#/$defs/capture"
        }
      },
      "additionalProperties": false
    },
    "capture": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "patterns": {
          "$ref": "#/$defs/patternList"
        }
      },
      "additionalProperties": true
    },
    "ruleContainer": {
      "type": "object",
      "properties": {
        "patterns": {
          "$ref": "#/$defs/patternList"
        }
      },
      "additionalProperties": true
    },
    "pattern": {
      "type": "object",
      "properties": {
        "include": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "contentName": {
          "type": "string"
        },
        "match": {
          "type": "string"
        },
        "begin": {
          "type": "string"
        },
        "end": {
          "type": "string"
        },
        "captures": {
          "$ref": "#/$defs/captures"
        },
        "beginCaptures": {
          "$ref": "#/$defs/captures"
        },
        "endCaptures": {
          "$ref": "#/$defs/captures"
        },
        "patterns": {
          "$ref": "#/$defs/patternList"
        },
        "applyEndPatternLast": {
          "type": "integer"
        }
      },
      "additionalProperties": true
    }
  }
}

=== Exymat/haproxy-vscode/syntaxes/haproxy-2.6.tmLanguage.json
{
  "$schema": "./tmlanguage.schema.json",
  "name": "HAProxy 2.6",
  "scopeName": "source.haproxy",
  "patterns": [
    {
      "include": "#comments"
    },
    {
      "include": "#preprocessor-directives"
    },
    {
      "include": "#strings"
    },
    {
      "include": "#sections"
    },
    {
      "include": "#directives-with-values"
    },
    {
      "include": "#directives-multiword"
    },
    {
      "include": "#cache-keywords"
    },
    {
      "include": "#schema-directives"
    },
    {
      "include": "#sample-fetches"
    },
    {
      "include": "#sample-function-calls"
    },
    {
      "include": "#acl-expressions"
    },
    {
      "include": "#sample-expressions"
    },
    {
      "include": "#rule-actions"
    },
    {
      "include": "#check-actions"
    },
    {
      "include": "#log-line"
    },
    {
      "include": "#bind-param-pairs"
    },
    {
      "include": "#single-arg-directives"
    },
    {
      "include": "#redirect-keywords"
    },
    {
      "include": "#addresses"
    },
    {
      "include": "#http-methods"
    },
    {
      "include": "#versions"
    },
    {
      "include": "#sample-fetches"
    },
    {
      "include": "#numbers"
    },
    {
      "include": "#acl-flags"
    },
    {
      "include": "#comparison-operators"
    },
    {
      "include": "#condition-keywords"
    },
    {
      "include": "#boolean-literals"
    },
    {
      "include": "#enums"
    },
    {
      "include": "#modifiers"
    },
    {
      "include": "#expressions"
    },
    {
      "include": "#filenames"
    },
    {
      "include": "#punctuation"
    },
    {
      "include": "#identifiers"
    }
  ],
  "repository": {
    "comments": {
      "patterns": [
        {
          "name": "comment.line.number-sign.haproxy",
          "match": "^\\s*#.*$"
        },
        {
          "name": "comment.line.number-sign.haproxy",
          "match": "#.*$"
        }
      ]
    },
    "preprocessor-directives": {
      "patterns": [
        {
          "name": "keyword.control.preprocessor.haproxy",
          "match": "^\\s*\\.(?:if|elif|else|endif|diag|notice|warning|alert)\\b"
        }
      ]
    },
    "strings": {
      "patterns": [
        {
          "name": "string.quoted.double.haproxy",
          "begin": "\"",
          "end": "\"",
          "patterns": [
            {
              "name": "constant.character.escape.haproxy",
              "match": "\\\\."
            }
          ]
        },
        {
          "name": "string.quoted.single.haproxy",
          "begin": "'",
          "end": "'",
          "patterns": [
            {
              "name": "constant.character.escape.haproxy",
              "match": "\\\\."
            }
          ]
        }
      ]
    },
    "sections": {
      "patterns": [
        {
          "match": "(?m)^(?:\\t| )*(defaults)\\s+(\\S+)(?:\\s+(from)\\s+(\\S+))?",
          "captures": {
            "1": {
              "name": "entity.name.type.section.haproxy"
            },
            "2": {
              "name": "entity.name.type.class.proxy.haproxy"
            },
            "3": {
              "name": "keyword.other.directive.haproxy"
            },
            "4": {
              "name": "entity.name.type.proxy.haproxy"
            }
          }
        },
        {
          "match": "(?m)^(?:\\t| )*((?:frontend|backend|listen))\\s+(\\S+)(?:\\s+(from)\\s+(\\S+))?",
          "captures": {
            "1": {
              "name": "entity.name.type.section.haproxy"
            },
            "2": {
              "name": "entity.name.type.class.proxy.haproxy"
            },
            "3": {
              "name": "keyword.other.directive.haproxy"
            },
            "4": {
              "name": "entity.name.type.proxy.haproxy"
            }
          }
        },
        {
          "match": "(?m)^(?:\\t| )*((?:http\\-errors|resolvers|userlist|crt\\-list|fcgi\\-app|mailers|program|peers|cache|ring))\\s+(\\S+)",
          "captures": {
            "1": {
              "name": "entity.name.type.section.haproxy"
            },
            "2": {
              "name": "entity.name.type.class.proxy.haproxy"
            }
          }
        },
        {
          "name": "entity.name.type.section.haproxy",
          "match": "(?m)^(?:\\t| )*((?:http\\-errors|resolvers|frontend|defaults|userlist|crt\\-list|fcgi\\-app|backend|mailers|program|listen|global|peers|cache|ring))\\b"
        }
      ]
    },
    "cache-keywords": {
      "patterns": [
        {
          "name": "keyword.other.directive.haproxy",
          "match": "\\b(?:max\\-secondary\\-entries|max\\-object\\-size|total\\-max\\-size|process\\-vary|max\\-age)\\b"
        }
      ]
    },
    "schema-directives": {
      "patterns": [
        {
          "name": "keyword.other.directive.haproxy",
          "match": "\\b(?:tune\\.quic\\.frontend\\.conn\\-tx\\-buffers\\.limit|h2\\-workaround\\-bogus\\-websocket\\-clients|tune\\.quic\\.frontend\\.max\\-streams\\-bidi|harden\\.reject\\-privileged\\-ports\\.quic|tune\\.quic\\.frontend\\.max\\-idle\\-timeout|harden\\.reject\\-privileged\\-ports\\.tcp|h1\\-accept\\-payload\\-with\\-any\\-method|tune\\.ssl\\.capture\\-cipherlist\\-size|ssl\\-default\\-server\\-ciphersuites|tune\\.h2\\.max\\-concurrent\\-streams|expose\\-experimental\\-directives|tune\\.peers\\.max\\-updates\\-at\\-once|deviceatlas\\-properties\\-cookie|ssl\\-default\\-bind\\-ciphersuites|tune\\.ssl\\.force\\-private\\-cache|tune\\.ssl\\.capture\\-buffer\\-size|httpclient\\.resolvers\\.prefer|tune\\.h2\\.initial\\-window\\-size|tune\\.ssl\\.ssl\\-ctx\\-cache\\-size|load\\-server\\-state\\-from\\-file|ssl\\-default\\-server\\-options|ssl\\-default\\-server\\-ciphers|tune\\.listener\\.multi\\-queue|tune\\.h2\\.header\\-table\\-size|tune\\.vars\\.reqres\\-max\\-size|tune\\.vars\\.global\\-max\\-size|tune\\.ssl\\.default\\-dh\\-param|tune\\.quic\\.retry\\-threshold|tune\\.lua\\.session\\-timeout|tune\\.lua\\.service\\-timeout|tune\\.vars\\.check\\-max\\-size|ssl\\-default\\-bind\\-ciphers|ssl\\-default\\-bind\\-options|tune\\.quic\\.reorder\\-ratio|tune\\.vars\\.proc\\-max\\-size|httpclient\\.resolvers\\.id|ssl\\-skip\\-self\\-issued\\-ca|tune\\.pool\\-high\\-fd\\-ratio|tune\\.vars\\.sess\\-max\\-size|tune\\.pattern\\.cache\\-size|tune\\.ssl\\.hard\\-maxrecord|ssl\\-default\\-bind\\-curves|insecure\\-setuid\\-wanted|ssl\\-load\\-extra\\-del\\-ext|tune\\.fd\\.edge\\-triggered|httpclient\\.ssl\\.ca\\-file|tune\\.h2\\.max\\-frame\\-size|tune\\.pool\\-low\\-fd\\-ratio|tune\\.vars\\.txn\\-max\\-size|tune\\.sched\\.low\\-latency|server\\-state\\-file\\-name|httpclient\\.ssl\\.verify|max\\-session\\-srv\\-conns|deviceatlas\\-log\\-level|tune\\.idle\\-pool\\.shared|tune\\.lua\\.task\\-timeout|http\\-send\\-name\\-header|deviceatlas\\-json\\-file|deviceatlas\\-separator|tune\\.lua\\.forced\\-yield|max\\-secondary\\-entries|accepted_payload_size|pp2\\-never\\-send\\-local|tune\\.buffers\\.reserve|tune\\.zlib\\.windowsize|max\\-keep\\-alive\\-queue|ssl\\-load\\-extra\\-files|insecure\\-fork\\-wanted|http\\-after\\-response|mworker\\-max\\-reloads|tune\\.runqueue\\-depth|tune\\.http\\.cookielen|h1\\-case\\-adjust\\-file|lua\\-load\\-per\\-thread|hash\\-balance\\-factor|tune\\.http\\.logurilen|tune\\.buffers\\.limit|tune\\.sndbuf\\.server|tune\\.ssl\\.maxrecord|tune\\.ssl\\.cachesize|tune\\.maxpollevents|tune\\.rcvbuf\\.client|tune\\.comp\\.maxlevel|issuers\\-chain\\-path|dynamic\\-cookie\\-key|no\\-memory\\-trimming|tune\\.zlib\\.memlevel|tune\\.rcvbuf\\.server|tune\\.sndbuf\\.client|server\\-state\\-base|max\\-spread\\-checks|ssl\\-dh\\-param\\-file|tune\\.ssl\\.lifetime|close\\-spread\\-time|parse\\-resolv\\-conf|ssl\\-provider\\-path|log\\-send\\-hostname|ssl\\-server\\-verify|profiling\\.memory|tune\\.recv_enough|unique\\-id\\-header|numa\\-cpu\\-mapping|lua\\-prepend\\-path|unique\\-id\\-format|error\\-log\\-format|tune\\.http\\.maxhdr|server\\-template|tune\\.fail\\-alloc|hard\\-stop\\-after|tune\\.lua\\.maxmem|max\\-object\\-size|profiling\\.tasks|tune\\.ssl\\.keylog|resolve_retries|maxcompcpuusage|tune\\.maxrewrite|default_backend|clitcpka\\-intvl|default\\-server|ssl\\-mode\\-async|srvtcpka\\-intvl|tune\\.maxaccept|cluster\\-secret|total\\-max\\-size|ignore\\-persist|tune\\.idletimer|nogetaddrinfo|thread\\-groups|saml\\-sso\\-load|http\\-response|ssl\\-propquery|log\\-format\\-sd|strict\\-limits|spread\\-checks|fd\\-hard\\-limit|srvtcpka\\-idle|force\\-persist|clitcpka\\-idle|master\\-worker|tune\\.pipesize|tune\\.bufsize|default\\-bind|zero\\-warning|http\\-request|bind\\-process|backing\\-file|process\\-vary|tcp\\-response|use\\-fcgi\\-app|set\\-dumpable|busy\\-polling|srvtcpka\\-cnt|default\\-path|thread\\-group|clitcpka\\-cnt|pass\\-header|log\\-forward|module\\-path|compression|module\\-load|monitor\\-uri|maxcomprate|noreuseport|maxconnrate|use_backend|http\\-errors|description|errorloc303|tcp\\-request|maxsessrate|errorloc302|maxsslconn|clitimeout|http\\-error|maxsslrate|errorfiles|http\\-check|http\\-reuse|contimeout|dgram\\-bind|nameserver|maxzlibmem|rate\\-limit|ssl\\-engine|use\\-server|log\\-stderr|srvtimeout|presetenv|hash\\-type|set\\-param|unix\\-bind|localpeer|noevports|path\\-info|errorfile|retry\\-on|maxpipes|errorloc|nosplice|nokqueue|unsetenv|ulimit\\-n|crt\\-base|dispatch|userlist|nbthread|fullconn|resetenv|retries|mailers|log\\-tag|max\\-age|pidfile|program|docroot|noepoll|declare|ca\\-base|command|timeout|cpu\\-map|balance|daemon|filter|nopoll|format|option|mailer|maxlen|setenv|chroot|peers|index|grace|quiet|table|stats|mode|peer|node|size|ring|hold|acl)\\b"
        }
      ]
    },
    "directives-with-values": {
      "patterns": [
        {
